import "@fontsource-variable/inter";
import "@fontsource-variable/jetbrains-mono";
import React, { useEffect, useState } from "react";
import {
  AbsoluteFill,
  Audio,
  continueRender,
  delayRender,
  Easing,
  interpolate,
  Sequence,
  spring,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
} from "remotion";

// Keynote-style launch film: black stage, big type, one idea per scene. 1920×1080, 30 fps.
// The music is generated by scripts/soundtrack.py and follows the same timings (120 BPM:
// one beat = 15 frames, one bar = 60 frames), so keep both in sync when moving scenes.

const C = {
  bg: "#000000",
  text: "#F5F5F7",
  muted: "#86868B",
  mint: "#3ECFA0",
  cyan: "#38C6FF",
  violet: "#8B6CFF",
  tile: "#101012",
  line: "rgba(255,255,255,0.10)",
};
const GRAD = `linear-gradient(90deg, ${C.mint} 0%, ${C.cyan} 35%, ${C.violet} 65%, ${C.mint} 100%)`;
const WARM = "linear-gradient(90deg, #FFD37A 0%, #FF7AB6 45%, #8B6CFF 80%, #FFD37A 100%)";
const SANS = "'Inter Variable', Inter, system-ui, sans-serif";
const MONO = "'JetBrains Mono Variable', ui-monospace, monospace";

const EXPO = Easing.bezier(0.16, 1, 0.3, 1);
const clamp = { extrapolateLeft: "clamp", extrapolateRight: "clamp" } as const;
const tw = (f: number, input: [number, number], output: [number, number], easing = EXPO) =>
  interpolate(f, input, output, { ...clamp, easing });

/** Scene timings in frames. */
const S = {
  open: { from: 0, dur: 150 },
  title: { from: 150, dur: 150 },
  click: { from: 300, dur: 240 },
  restore: { from: 540, dur: 180 },
  launchers: { from: 720, dur: 180 },
  home: { from: 900, dur: 120 },
  menu: { from: 1020, dur: 120 },
  bento: { from: 1140, dur: 240 },
  automate: { from: 1380, dur: 180 },
  interfaces: { from: 1560, dur: 180 },
  trust: { from: 1740, dur: 120 },
  finale: { from: 1860, dur: 240 },
};
export const KEYNOTE_DURATION = S.finale.from + S.finale.dur;

// ───────────────────────── building blocks ─────────────────────────

/** Gradient-filled text; the gradient slowly drifts so the colour feels alive. */
const gradText = (f: number, gradient = GRAD): React.CSSProperties => ({
  backgroundImage: gradient,
  backgroundSize: "300% 100%",
  backgroundPosition: `${(f * 0.35) % 300}% 0`,
  WebkitBackgroundClip: "text",
  backgroundClip: "text",
  color: "transparent",
  paddingBottom: "0.1em",
  marginBottom: "-0.1em",
});

type Word = string | { t: string; grad?: boolean; warm?: boolean; muted?: boolean };

/** A line of type whose words arrive one after another, out of a blur. */
const Line: React.FC<{
  words: Word[];
  at?: number;
  size: number;
  weight?: number;
  stagger?: number;
  color?: string;
  align?: "center" | "flex-start";
  style?: React.CSSProperties;
}> = ({ words, at = 0, size, weight = 700, stagger = 4, color = C.text, align = "center", style }) => {
  const f = useCurrentFrame();
  return (
    <div
      style={{
        display: "flex",
        flexWrap: "wrap",
        justifyContent: align,
        columnGap: size * 0.26,
        fontFamily: SANS,
        fontSize: size,
        fontWeight: weight,
        letterSpacing: "-0.035em",
        lineHeight: 1.05,
        color,
        ...style,
      }}
    >
      {words.map((w, i) => {
        const word = typeof w === "string" ? { t: w } : w;
        const t = f - at - i * stagger;
        const extra = word.grad ? gradText(f) : word.warm ? gradText(f, WARM) : word.muted ? { color: C.muted } : {};
        return (
          <span
            key={i}
            style={{
              display: "inline-block",
              opacity: tw(t, [0, 12], [0, 1], Easing.linear),
              filter: `blur(${tw(t, [0, 18], [18, 0])}px)`,
              translate: `0 ${tw(t, [0, 22], [size * 0.3, 0])}px`,
              ...extra,
            }}
          >
            {word.t}
          </span>
        );
      })}
    </div>
  );
};

/** Wraps a scene: a soft fade in, then blur + zoom out into black. */
const Scene: React.FC<{ from: number; dur: number; children: React.ReactNode }> = ({ from, dur, children }) => (
  <Sequence from={from} durationInFrames={dur}>
    <SceneFx dur={dur}>{children}</SceneFx>
  </Sequence>
);

const SceneFx: React.FC<{ dur: number; children: React.ReactNode }> = ({ dur, children }) => {
  const f = useCurrentFrame();
  const out = tw(f, [dur - 14, dur], [0, 1], Easing.in(Easing.cubic));
  return (
    <AbsoluteFill
      style={{
        opacity: tw(f, [0, 8], [0, 1], Easing.linear) * (1 - out),
        filter: out > 0 ? `blur(${out * 16}px)` : undefined,
        scale: String(1 + out * 0.06),
      }}
    >
      {children}
    </AbsoluteFill>
  );
};

/** A dim coloured light behind the content. */
const Glow: React.FC<{ color?: string; x?: number; y?: number; size?: number; opacity?: number }> = ({
  color = C.mint,
  x = 960,
  y = 700,
  size = 1300,
  opacity = 0.22,
}) => {
  const f = useCurrentFrame();
  const breathe = 1 + Math.sin(f / 40) * 0.05;
  return (
    <div
      style={{
        position: "absolute",
        left: x - (size * breathe) / 2,
        top: y - (size * breathe * 0.6) / 2,
        width: size * breathe,
        height: size * breathe * 0.6,
        borderRadius: "50%",
        background: `radial-gradient(closest-side, ${color}, transparent)`,
        opacity,
        filter: "blur(40px)",
      }}
    />
  );
};

const Center: React.FC<{ top?: number; children: React.ReactNode }> = ({ top, children }) => (
  <div
    style={{
      position: "absolute",
      left: 0,
      right: 0,
      top,
      ...(top === undefined ? { top: 0, bottom: 0, display: "flex", flexDirection: "column", justifyContent: "center" } : {}),
    }}
  >
    {children}
  </div>
);

/** The app icon (monitor with a prompt, console base with a power button), drawn in strokes. */
const Logo: React.FC<{ size: number; draw: number; glow?: number }> = ({ size, draw, glow = 0 }) => {
  const seg = (a: number, b: number) => {
    const p = interpolate(draw, [a, b], [0, 1], clamp);
    return { strokeDasharray: 1, strokeDashoffset: 1 - p, opacity: p > 0 ? 1 : 0 };
  };
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 256 256"
      style={{ overflow: "visible", filter: glow > 0 ? `drop-shadow(0 0 ${30 * glow}px ${C.mint}aa)` : undefined }}
    >
      <rect x="22" y="14" width="212" height="150" rx="24" fill="none" stroke={C.text} strokeWidth="14" pathLength={1} style={seg(0, 0.45)} />
      <path d="M72 62 L112 90 L72 118" fill="none" stroke={C.mint} strokeWidth="16" strokeLinecap="round" strokeLinejoin="round" pathLength={1} style={seg(0.35, 0.6)} />
      <path d="M124 122 L176 122" fill="none" stroke={C.mint} strokeWidth="16" strokeLinecap="round" pathLength={1} style={seg(0.5, 0.7)} />
      <rect x="6" y="182" width="244" height="62" rx="16" fill="#1c1c1f" fillOpacity={interpolate(draw, [0.6, 1], [0, 1], clamp)} stroke={C.text} strokeWidth="12" pathLength={1} style={seg(0.45, 0.85)} />
      <path d="M34 213 L54 213" stroke={C.mint} strokeWidth="12" strokeLinecap="round" pathLength={1} style={seg(0.8, 0.95)} />
      <path d="M200 203 A14 14 0 1 0 220 203" fill="none" stroke={C.mint} strokeWidth="9" strokeLinecap="round" pathLength={1} style={seg(0.82, 1)} />
      <path d="M210 196 L210 212" stroke={C.mint} strokeWidth="9" strokeLinecap="round" pathLength={1} style={seg(0.85, 1)} />
    </svg>
  );
};

/** A stylised game: dusk sky, sun, parallax hills. */
const Game: React.FC<{ dim?: number }> = ({ dim = 0 }) => {
  const f = useCurrentFrame();
  return (
    <AbsoluteFill style={{ background: "linear-gradient(180deg,#141d3b 0%,#3a4f86 38%,#d9866b 78%,#f3c27a 100%)", overflow: "hidden" }}>
      <div style={{ position: "absolute", left: "62%", top: "30%", width: "13%", aspectRatio: "1", borderRadius: "50%", background: "#ffe3b0", boxShadow: "0 0 120px 40px #ffb86a88" }} />
      {[0, 1, 2].map((i) => (
        <div
          key={i}
          style={{
            position: "absolute",
            left: `${-30 + i * 35 - ((f * (0.08 + i * 0.05)) % 40)}%`,
            bottom: `${-28 + i * 6}%`,
            width: "95%",
            height: `${70 - i * 12}%`,
            borderRadius: "50% 50% 0 0",
            background: ["#1b2a3a", "#223a3c", "#2c4a3e"][i],
          }}
        />
      ))}
      {[0, 1, 2].map((i) => (
        <div
          key={`b${i}`}
          style={{
            position: "absolute",
            left: `${95 + i * 30 - ((f * (0.13 + i * 0.05)) % 140)}%`,
            bottom: `${-22 + i * 4}%`,
            width: "80%",
            height: `${48 - i * 8}%`,
            borderRadius: "50% 50% 0 0",
            background: ["#1b2a3a", "#223a3c", "#2c4a3e"][i],
          }}
        />
      ))}
      <AbsoluteFill style={{ background: `rgba(0,0,0,${dim})` }} />
    </AbsoluteFill>
  );
};

/** Windows-like desktop wallpaper, optionally with the Console Mode window on it. */
const Desktop: React.FC<{ app?: boolean; pressed?: number }> = ({ app, pressed = 0 }) => (
  <AbsoluteFill style={{ background: "radial-gradient(120% 90% at 30% 110%, #3656d9 0%, #1d2a6b 45%, #0b1030 100%)" }}>
    <div style={{ position: "absolute", left: "8%", top: "10%", width: "46%", height: "44%", borderRadius: 6, background: "rgba(255,255,255,0.10)", border: "1px solid rgba(255,255,255,0.16)" }} />
    <div style={{ position: "absolute", left: "44%", top: "32%", width: "44%", height: "40%", borderRadius: 6, background: "rgba(255,255,255,0.08)", border: "1px solid rgba(255,255,255,0.14)" }} />
    {app && (
      <div
        style={{
          position: "absolute",
          left: "22%",
          top: "18%",
          width: "56%",
          height: "62%",
          borderRadius: 8,
          background: "#1d1d21",
          border: "1px solid rgba(255,255,255,0.18)",
          boxShadow: "0 12px 30px rgba(0,0,0,0.5)",
        }}
      >
        <div style={{ height: "18%", display: "flex", alignItems: "center", gap: 6, paddingLeft: 10 }}>
          <Logo size={16} draw={1} />
          <span style={{ fontFamily: SANS, fontSize: 11, color: C.text, fontWeight: 600 }}>Console Mode</span>
        </div>
        <div
          style={{
            position: "absolute",
            left: "50%",
            top: "70%",
            translate: "-50% -50%",
            scale: String(1 - pressed * 0.1),
            padding: "8px 22px",
            borderRadius: 999,
            background: C.mint,
            color: "#04110c",
            fontFamily: SANS,
            fontWeight: 700,
            fontSize: 14,
            whiteSpace: "nowrap",
            boxShadow: `0 0 ${18 + pressed * 20}px ${C.mint}88`,
          }}
        >
          Play now
        </div>
        <div style={{ position: "absolute", left: "12%", top: "28%", width: "76%", height: 8, borderRadius: 4, background: "rgba(255,255,255,0.12)" }} />
        <div style={{ position: "absolute", left: "12%", top: "40%", width: "50%", height: 8, borderRadius: 4, background: "rgba(255,255,255,0.08)" }} />
      </div>
    )}
    <div style={{ position: "absolute", left: 0, right: 0, bottom: 0, height: "8%", background: "rgba(20,20,30,0.75)" }} />
  </AbsoluteFill>
);

/** A screen with a bezel. `power` 0 = off, 1 = on; `tvOn` plays the power-on flash. */
const Screen: React.FC<{
  x: number;
  y: number;
  w: number;
  h: number;
  power: number;
  kind: "monitor" | "tv";
  children: React.ReactNode;
}> = ({ x, y, w, h, power, kind, children }) => (
  <div style={{ position: "absolute", left: x, top: y, width: w }}>
    <div
      style={{
        width: w,
        height: h,
        padding: kind === "tv" ? 10 : 8,
        boxSizing: "border-box",
        borderRadius: kind === "tv" ? 10 : 14,
        background: "#0a0a0c",
        border: "1.5px solid rgba(255,255,255,0.16)",
        boxShadow: power > 0.5 ? "0 30px 90px rgba(80,140,255,0.18)" : "0 30px 60px rgba(0,0,0,0.6)",
      }}
    >
      <div style={{ position: "relative", width: "100%", height: "100%", overflow: "hidden", borderRadius: 4, background: "#000" }}>
        {children}
        <AbsoluteFill style={{ background: "#000", opacity: 1 - power }} />
      </div>
    </div>
    {kind === "monitor" ? (
      <>
        <div style={{ width: 40, height: 60, margin: "0 auto", background: "linear-gradient(180deg,#2a2a2e,#18181b)" }} />
        <div style={{ width: 170, height: 10, margin: "0 auto", borderRadius: 5, background: "#2a2a2e" }} />
      </>
    ) : (
      <div style={{ display: "flex", justifyContent: "space-between", padding: "0 18%" }}>
        <div style={{ width: 60, height: 26, background: "#2a2a2e", clipPath: "polygon(40% 0,60% 0,100% 100%,0 100%)" }} />
        <div style={{ width: 60, height: 26, background: "#2a2a2e", clipPath: "polygon(40% 0,60% 0,100% 100%,0 100%)" }} />
      </div>
    )}
  </div>
);

const Cursor: React.FC<{ x: number; y: number; scale?: number }> = ({ x, y, scale = 1 }) => (
  <svg width="34" height="44" viewBox="0 0 17 22" style={{ position: "absolute", left: x, top: y, scale: String(scale), transformOrigin: "0 0", filter: "drop-shadow(0 4px 6px rgba(0,0,0,0.6))" }}>
    <path d="M1 1 L1 17 L5 13 L8 20 L11 19 L8 12 L14 12 Z" fill="#fff" stroke="#000" strokeWidth="1.2" strokeLinejoin="round" />
  </svg>
);

const Check: React.FC<{ p: number; size?: number }> = ({ p, size = 56 }) => (
  <div
    style={{
      width: size,
      height: size,
      borderRadius: size / 2,
      background: `rgba(62,207,160,${0.15 + p * 0.85})`,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      scale: String(0.6 + 0.4 * p),
      boxShadow: p > 0.9 ? `0 0 30px ${C.mint}88` : undefined,
    }}
  >
    <svg width={size * 0.55} height={size * 0.55} viewBox="0 0 24 24">
      <path d="M4 12.5 L10 18 L20 6" fill="none" stroke="#03130d" strokeWidth="3.4" strokeLinecap="round" strokeLinejoin="round" pathLength={1} strokeDasharray={1} strokeDashoffset={1 - p} />
    </svg>
  </div>
);

type IconName = "screen" | "speaker" | "resize" | "volume" | "tv" | "fps" | "hdr" | "exit" | "play" | "menu" | "stop";

const Icon: React.FC<{ name: IconName; size?: number; color?: string }> = ({ name, size = 48, color = C.text }) => {
  const p = { fill: "none", stroke: color, strokeWidth: 2, strokeLinecap: "round" as const, strokeLinejoin: "round" as const };
  const paths: Record<IconName, React.ReactNode> = {
    screen: (
      <>
        <rect x="3" y="4" width="18" height="12" rx="2" {...p} />
        <path d="M9 20h6M12 16v4" {...p} />
      </>
    ),
    speaker: (
      <>
        <path d="M4 9h4l5-4v14l-5-4H4z" {...p} />
        <path d="M16.5 8.5a5 5 0 0 1 0 7M19 6a8.5 8.5 0 0 1 0 12" {...p} />
      </>
    ),
    resize: (
      <>
        <path d="M4 9V4h5M20 15v5h-5M4 4l6 6M20 20l-6-6" {...p} />
      </>
    ),
    volume: (
      <>
        <path d="M4 9h4l5-4v14l-5-4H4z" {...p} />
        <path d="M17 9.5a3.5 3.5 0 0 1 0 5" {...p} />
      </>
    ),
    tv: (
      <>
        <rect x="2.5" y="5" width="19" height="12" rx="1.5" {...p} />
        <path d="M7 20h10" {...p} />
      </>
    ),
    fps: <path d="M4 18a8 8 0 1 1 16 0M12 18l4-6" {...p} />,
    hdr: (
      <>
        <circle cx="12" cy="12" r="4.5" {...p} />
        <path d="M12 2.5v2M12 19.5v2M2.5 12h2M19.5 12h2M5.3 5.3l1.4 1.4M17.3 17.3l1.4 1.4M5.3 18.7l1.4-1.4M17.3 6.7l1.4-1.4" {...p} />
      </>
    ),
    exit: <path d="M14 4h5v16h-5M10 8l-4 4 4 4M6 12h10" {...p} />,
    play: <path d="M8 5l11 7-11 7z" fill={color} stroke={color} strokeWidth={2} strokeLinejoin="round" />,
    menu: <path d="M5 7h14M5 12h14M5 17h14" {...p} strokeWidth={2.4} />,
    stop: <rect x="6" y="6" width="12" height="12" rx="2" fill={color} />,
  };
  return (
    <svg width={size} height={size} viewBox="0 0 24 24">
      {paths[name]}
    </svg>
  );
};

// ───────────────────────── scenes ─────────────────────────

const ColdOpen: React.FC = () => (
  <AbsoluteFill>
    <Glow color={C.violet} y={620} opacity={0.12} />
    <Center>
      <Line words={["What", "if", "your", "PC"]} at={12} size={128} stagger={6} />
      <div style={{ height: 18 }} />
      <Line words={["was", "a", { t: "console?", grad: true }]} at={52} size={128} stagger={7} />
    </Center>
  </AbsoluteFill>
);

const Title: React.FC = () => {
  const f = useCurrentFrame();
  const { fps } = useVideoConfig();
  const pop = spring({ frame: f, fps, config: { damping: 18, stiffness: 90 } });
  const tracking = tw(f, [14, 60], [0.28, -0.045]);
  const sweep = tw(f, [30, 90], [-30, 130], Easing.inOut(Easing.cubic));
  return (
    <AbsoluteFill>
      <Glow color={C.mint} y={560} opacity={0.18 + pop * 0.08} size={1500} />
      <Center>
        <div style={{ display: "flex", justifyContent: "center", scale: String(0.8 + pop * 0.2) }}>
          <Logo size={220} draw={tw(f, [0, 40], [0, 1], Easing.inOut(Easing.cubic))} glow={tw(f, [30, 60], [0, 1])} />
        </div>
        <div style={{ height: 50 }} />
        <div
          style={{
            textAlign: "center",
            fontFamily: SANS,
            fontSize: 196,
            fontWeight: 800,
            letterSpacing: `${tracking}em`,
            lineHeight: 1,
            opacity: tw(f, [14, 34], [0, 1], Easing.linear),
            filter: `blur(${tw(f, [14, 44], [24, 0])}px)`,
            backgroundImage: `linear-gradient(100deg, ${C.text} ${sweep - 20}%, #ffffff ${sweep - 6}%, ${C.mint} ${sweep}%, #ffffff ${sweep + 6}%, ${C.text} ${sweep + 20}%)`,
            WebkitBackgroundClip: "text",
            backgroundClip: "text",
            color: "transparent",
            paddingBottom: 12,
          }}
        >
          Console Mode
        </div>
        <div style={{ height: 26 }} />
        <Line words={["For", "Windows", "10", "and", "11."]} at={64} size={44} weight={500} stagger={2} color={C.muted} />
      </Center>
    </AbsoluteFill>
  );
};

const OneClick: React.FC = () => {
  const f = useCurrentFrame();
  const click = 90;
  const pressed = interpolate(f, [click - 3, click, click + 6], [0, 1, 0], clamp);
  const monA = 1 - tw(f, [105, 113], [0, 1], Easing.linear);
  const monB = 1 - tw(f, [120, 128], [0, 1], Easing.linear);
  const tvOn = tw(f, [135, 145], [0, 1], Easing.out(Easing.cubic));
  const flash = interpolate(f, [135, 139, 150], [0, 1, 0], clamp);
  const push = tw(f, [140, 238], [0, 1], Easing.inOut(Easing.cubic));
  const cx = interpolate(f, [30, 82], [700, 810], { ...clamp, easing: Easing.inOut(Easing.cubic) });
  const cy = interpolate(f, [30, 82], [930, 676], { ...clamp, easing: Easing.inOut(Easing.cubic) });
  const ripple = tw(f, [click, click + 20], [0, 1]);
  return (
    <AbsoluteFill>
      <Glow color={tvOn > 0 ? "#ff9c6b" : C.cyan} x={tvOn > 0 ? 1440 : 800} y={700} opacity={0.1 + tvOn * 0.1} />
      <Center top={100}>
        <Line words={["One", { t: "click.", grad: true }]} at={4} size={118} stagger={6} />
        <div style={{ height: 22 }} />
        <Line words={["The", "TV", "takes", "over.", { t: "The", muted: true }, { t: "desk", muted: true }, { t: "goes", muted: true }, { t: "dark.", muted: true }]} at={140} size={48} weight={600} stagger={3} />
      </Center>
      <AbsoluteFill style={{ perspective: 2200 }}>
        <AbsoluteFill
          style={{
            transformOrigin: "1450px 640px",
            scale: String(1 + push * 0.14),
            translate: `${-push * 120}px ${push * 20}px`,
            rotate: "x 7deg",
            transformStyle: "preserve-3d",
          }}
        >
          <Screen x={150} y={520} w={420} h={250} power={monA} kind="monitor">
            <Desktop />
          </Screen>
          <Screen x={600} y={520} w={420} h={250} power={monB} kind="monitor">
            <Desktop app pressed={pressed} />
          </Screen>
          <Screen x={1100} y={430} w={700} h={400} power={1} kind="tv">
            <AbsoluteFill style={{ scale: `1 ${Math.max(0.005, tvOn)}`, opacity: tvOn > 0 ? 1 : 0 }}>
              <Game />
            </AbsoluteFill>
            <AbsoluteFill style={{ background: "#fff", opacity: flash * 0.7 }} />
          </Screen>
          {f >= click && f < click + 20 && (
            <div
              style={{
                position: "absolute",
                left: 810 - 60 * ripple,
                top: 676 - 60 * ripple,
                width: 120 * ripple,
                height: 120 * ripple,
                borderRadius: "50%",
                border: `3px solid ${C.mint}`,
                opacity: 1 - ripple,
              }}
            />
          )}
          {f >= 24 && f < 112 && <Cursor x={cx} y={cy} scale={1 - pressed * 0.15} />}
        </AbsoluteFill>
      </AbsoluteFill>
    </AbsoluteFill>
  );
};

const Restore: React.FC = () => {
  const f = useCurrentFrame();
  const chips: { icon: IconName; label: string; at: number }[] = [
    { icon: "screen", label: "Screens", at: 45 },
    { icon: "speaker", label: "Audio", at: 60 },
    { icon: "resize", label: "Resolution", at: 75 },
  ];
  return (
    <AbsoluteFill>
      <Glow color={C.mint} y={760} opacity={0.14} />
      <Center top={230}>
        <Line words={["Quit", "the", "game."]} at={4} size={118} stagger={5} />
        <div style={{ height: 10 }} />
        <Line words={["Your", "desk", { t: "comes", grad: true }, { t: "back.", grad: true }]} at={22} size={118} stagger={5} />
      </Center>
      <div style={{ position: "absolute", top: 640, left: 0, right: 0, display: "flex", justifyContent: "center", gap: 36 }}>
        {chips.map((c) => {
          const t = f - c.at + 12;
          return (
            <div
              key={c.label}
              style={{
                width: 440,
                height: 124,
                borderRadius: 32,
                background: "linear-gradient(180deg,#18181b,#101012)",
                border: `1px solid ${C.line}`,
                display: "flex",
                alignItems: "center",
                gap: 22,
                padding: "0 28px",
                boxSizing: "border-box",
                opacity: tw(t, [0, 12], [0, 1], Easing.linear),
                translate: `0 ${tw(t, [0, 20], [60, 0])}px`,
                filter: `blur(${tw(t, [0, 16], [12, 0])}px)`,
              }}
            >
              <Icon name={c.icon} size={52} />
              <span style={{ flex: 1, fontFamily: SANS, fontSize: 44, fontWeight: 600, color: C.text, letterSpacing: "-0.02em" }}>{c.label}</span>
              <Check p={tw(f, [c.at, c.at + 12], [0, 1])} />
            </div>
          );
        })}
      </div>
      <Center top={850}>
        <Line words={["Screens,", "audio", "and", "resolution,", "exactly", "as", "you", "left", "them."]} at={96} size={36} weight={500} stagger={2} color={C.muted} />
      </Center>
    </AbsoluteFill>
  );
};

const Launchers: React.FC = () => {
  const f = useCurrentFrame();
  const { fps } = useVideoConfig();
  const cards = [
    { name: "Steam", sub: "Big Picture", bg: "linear-gradient(160deg,#1f3a57,#0c1522)", accent: "#66c0f4" },
    { name: "Playnite", sub: "Fullscreen", bg: "linear-gradient(160deg,#3b2466,#120b21)", accent: "#b690ff" },
    { name: "Xbox", sub: "Full-screen mode", bg: "linear-gradient(160deg,#1d4d24,#08170b)", accent: "#5fd36f" },
  ];
  return (
    <AbsoluteFill style={{ perspective: 2400 }}>
      <Glow color={C.violet} y={760} opacity={0.14} />
      <Center top={110}>
        <Line words={["Your", "library."]} at={4} size={112} stagger={5} />
        <div style={{ height: 8 }} />
        <Line words={["Your", "launcher."]} at={20} size={112} stagger={5} color={C.muted} />
      </Center>
      <div style={{ position: "absolute", top: 420, left: 0, right: 0, display: "flex", justifyContent: "center", gap: 48 }}>
        {cards.map((c, i) => {
          const s = spring({ frame: f - 30 - i * 15, fps, config: { damping: 16, stiffness: 80 } });
          const drift = Math.sin((f + i * 30) / 30) * 8;
          return (
            <div
              key={c.name}
              style={{
                width: 440,
                height: 520,
                borderRadius: 40,
                background: c.bg,
                border: "1px solid rgba(255,255,255,0.14)",
                boxShadow: `0 40px 100px rgba(0,0,0,0.6), 0 0 80px ${c.accent}22`,
                padding: 44,
                boxSizing: "border-box",
                display: "flex",
                flexDirection: "column",
                justifyContent: "flex-end",
                opacity: s,
                translate: `0 ${(1 - s) * 260 + drift}px`,
                rotate: `y ${(i - 1) * -10 * (0.4 + 0.6 * s)}deg`,
                position: "relative",
                overflow: "hidden",
              }}
            >
              <div style={{ position: "absolute", right: -80, top: -80, width: 320, height: 320, borderRadius: "50%", border: `40px solid ${c.accent}33` }} />
              <div style={{ position: "absolute", right: 30, top: 30, width: 110, height: 110, borderRadius: "50%", background: `radial-gradient(circle at 35% 35%, ${c.accent}, ${c.accent}44)` }} />
              <div style={{ fontFamily: SANS, fontSize: 76, fontWeight: 800, color: "#fff", letterSpacing: "-0.04em" }}>{c.name}</div>
              <div style={{ fontFamily: SANS, fontSize: 34, fontWeight: 500, color: c.accent, marginTop: 6 }}>{c.sub}</div>
            </div>
          );
        })}
      </div>
    </AbsoluteFill>
  );
};

const HoldHome: React.FC = () => {
  const f = useCurrentFrame();
  const fill = tw(f, [22, 80], [0, 1], Easing.inOut(Easing.quad));
  const done = f >= 80;
  const burst = tw(f, [80, 110], [0, 1]);
  const hold = f >= 20 && f < 82 ? 1 : 0;
  const R = 170;
  const circ = 2 * Math.PI * R;
  return (
    <AbsoluteFill>
      <Glow color={C.mint} y={600} opacity={0.08 + fill * 0.2} size={1000 + fill * 400} />
      <Center top={90}>
        <Line words={["Hold", { t: "Home.", grad: true }]} at={2} size={118} stagger={6} />
      </Center>
      <div style={{ position: "absolute", left: 960 - 220, top: 610 - 220, width: 440, height: 440 }}>
        <svg width={440} height={440} viewBox="0 0 440 440" style={{ position: "absolute", inset: 0, rotate: "-90deg" }}>
          <defs>
            <linearGradient id="ring" x1="0" y1="0" x2="1" y2="1">
              <stop offset="0" stopColor={C.mint} />
              <stop offset="1" stopColor={C.cyan} />
            </linearGradient>
          </defs>
          <circle cx="220" cy="220" r={R} fill="none" stroke="rgba(255,255,255,0.10)" strokeWidth="12" />
          <circle
            cx="220"
            cy="220"
            r={R}
            fill="none"
            stroke="url(#ring)"
            strokeWidth="12"
            strokeLinecap="round"
            strokeDasharray={circ}
            strokeDashoffset={circ * (1 - fill)}
            style={{ filter: `drop-shadow(0 0 ${10 + fill * 20}px ${C.mint})` }}
          />
        </svg>
        {done && (
          <div
            style={{
              position: "absolute",
              left: 220 - R * (1 + burst * 0.8),
              top: 220 - R * (1 + burst * 0.8),
              width: 2 * R * (1 + burst * 0.8),
              height: 2 * R * (1 + burst * 0.8),
              borderRadius: "50%",
              border: `6px solid ${C.mint}`,
              opacity: 1 - burst,
            }}
          />
        )}
        <div
          style={{
            position: "absolute",
            left: 220 - 115,
            top: 220 - 115,
            width: 230,
            height: 230,
            borderRadius: "50%",
            background: done ? `radial-gradient(circle at 40% 35%, #5fe0b6, ${C.mint} 60%, #1f8a67)` : "radial-gradient(circle at 40% 35%, #2c2c31, #151518)",
            border: "1.5px solid rgba(255,255,255,0.18)",
            boxShadow: done ? `0 0 80px ${C.mint}aa` : "inset 0 -10px 30px rgba(0,0,0,0.6), 0 20px 60px rgba(0,0,0,0.6)",
            scale: String(1 - hold * 0.06),
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <svg width="96" height="96" viewBox="0 0 24 24">
            <path d="M4 11 L12 4 L20 11 V20 H14.5 V14.5 H9.5 V20 H4 Z" fill="none" stroke={done ? "#03130d" : C.text} strokeWidth="1.8" strokeLinejoin="round" />
          </svg>
        </div>
      </div>
      <Center top={900}>
        <Line words={["Console", "mode,", "straight", "from", "the", "couch."]} at={84} size={44} weight={600} stagger={2} color={C.muted} />
      </Center>
    </AbsoluteFill>
  );
};

const SessionMenu: React.FC = () => {
  const f = useCurrentFrame();
  const tiles: { icon: IconName; label: string; value: string }[] = [
    { icon: "volume", label: "Volume", value: "72" },
    { icon: "resize", label: "Resolution", value: "4K" },
    { icon: "tv", label: "Audio", value: "TV" },
    { icon: "fps", label: "FPS limit", value: "60" },
    { icon: "hdr", label: "HDR", value: "On" },
    { icon: "exit", label: "Exit", value: "Desk" },
  ];
  const menuIn = tw(f, [16, 34], [0, 1]);
  let pos = 0;
  for (let k = 0; k < 4; k++) pos += tw(f, [45 + 15 * k, 53 + 15 * k], [0, 1]);
  const W = 222;
  const GAP = 22;
  const left = (1920 - (6 * W + 5 * GAP)) / 2;
  return (
    <AbsoluteFill>
      <Game dim={0.15 + menuIn * 0.45} />
      <Center top={120}>
        <Line words={["Select", "+", { t: "Y.", grad: true }]} at={2} size={112} stagger={5} style={{ textShadow: "0 6px 40px rgba(0,0,0,0.5)" }} />
        <div style={{ height: 14 }} />
        <Line words={["A", "menu", "over", "any", "game."]} at={14} size={46} weight={600} stagger={2} color="rgba(245,245,247,0.8)" />
      </Center>
      {tiles.map((t, i) => {
        const sel = Math.max(0, 1 - Math.abs(pos - i));
        const enter = tw(f - 16 - i * 3, [0, 18], [0, 1]);
        return (
          <div
            key={t.label}
            style={{
              position: "absolute",
              left: left + i * (W + GAP),
              top: 560,
              width: W,
              height: 250,
              borderRadius: 30,
              boxSizing: "border-box",
              padding: 26,
              background: `rgba(16,17,20,${0.72 + sel * 0.1})`,
              backdropFilter: "blur(24px)",
              border: `${1.5 + sel * 1.5}px solid ${sel > 0.5 ? C.mint : "rgba(255,255,255,0.14)"}`,
              boxShadow: sel > 0.3 ? `0 0 ${50 * sel}px ${C.mint}66` : "0 20px 50px rgba(0,0,0,0.5)",
              scale: String(0.94 + sel * 0.1),
              opacity: enter,
              translate: `0 ${(1 - enter) * 120}px`,
              display: "flex",
              flexDirection: "column",
              justifyContent: "space-between",
            }}
          >
            <Icon name={t.icon} size={44} color={sel > 0.5 ? C.mint : C.text} />
            <div>
              <div style={{ fontFamily: SANS, fontSize: 56, fontWeight: 800, color: C.text, letterSpacing: "-0.03em" }}>{t.value}</div>
              <div style={{ fontFamily: SANS, fontSize: 24, fontWeight: 500, color: C.muted }}>{t.label}</div>
            </div>
          </div>
        );
      })}
    </AbsoluteFill>
  );
};

const Tile: React.FC<{ x: number; y: number; w: number; h: number; at: number; children: React.ReactNode }> = ({ x, y, w, h, at, children }) => {
  const f = useCurrentFrame();
  const t = f - at;
  return (
    <div
      style={{
        position: "absolute",
        left: x,
        top: y,
        width: w,
        height: h,
        borderRadius: 40,
        background: "linear-gradient(180deg,#161618,#0c0c0e)",
        border: `1px solid ${C.line}`,
        padding: 44,
        boxSizing: "border-box",
        overflow: "hidden",
        opacity: tw(t, [0, 12], [0, 1], Easing.linear),
        scale: String(tw(t, [0, 26], [0.92, 1])),
        filter: `blur(${tw(t, [0, 18], [14, 0])}px)`,
      }}
    >
      {children}
    </div>
  );
};

const Caption: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <div style={{ position: "absolute", left: 44, bottom: 40, right: 44, fontFamily: SANS, fontSize: 28, fontWeight: 500, color: C.muted, letterSpacing: "-0.01em" }}>{children}</div>
);

const Bento: React.FC = () => {
  const f = useCurrentFrame();
  const L = 160;
  const T = 290;
  const G = 24;
  const cw = (1600 - 2 * G) / 3;
  const rh = 330;
  const hz = Math.round(tw(f, [30, 90], [60, 120], Easing.out(Easing.quad)));
  const fps = Math.round(tw(f, [60, 110], [240, 60], Easing.out(Easing.quad)));
  const big: React.CSSProperties = { fontFamily: SANS, fontWeight: 800, letterSpacing: "-0.05em", lineHeight: 1 };
  return (
    <AbsoluteFill style={{ scale: String(tw(f, [0, 240], [1.04, 1], Easing.linear)) }}>
      <Glow color={C.cyan} y={640} opacity={0.12} size={1800} />
      <Center top={110}>
        <Line words={["Pro,", "under", "the", { t: "hood.", grad: true }]} at={2} size={104} stagger={5} />
      </Center>
      <Tile x={L} y={T} w={cw * 2 + G} h={rh} at={20}>
        <div style={{ display: "flex", alignItems: "baseline", gap: 40 }}>
          <span style={{ ...big, fontSize: 210, ...gradText(f) }}>4K</span>
          <span style={{ ...big, fontSize: 150, color: C.text }}>
            {hz}
            <span style={{ fontSize: 70, color: C.muted, marginLeft: 10 }}>Hz</span>
          </span>
        </div>
        <Caption>Resolution and refresh rate, per screen.</Caption>
      </Tile>
      <Tile x={L + 2 * (cw + G)} y={T} w={cw} h={rh} at={28}>
        <span style={{ ...big, fontSize: 170, ...gradText(f, WARM) }}>HDR</span>
        <Caption>On while you play.</Caption>
      </Tile>
      <Tile x={L} y={T + rh + G} w={cw} h={rh} at={36}>
        <span style={{ ...big, fontSize: 170, color: C.text }}>VRR</span>
        <Caption>Variable refresh rate.</Caption>
      </Tile>
      <Tile x={L + cw + G} y={T + rh + G} w={cw} h={rh} at={44}>
        <span style={{ ...big, fontSize: 170, color: C.text }}>
          {fps}
          <span style={{ fontSize: 60, color: C.muted, marginLeft: 12 }}>fps</span>
        </span>
        <Caption>FPS limit, powered by RTSS.</Caption>
      </Tile>
      <Tile x={L + 2 * (cw + G)} y={T + rh + G} w={cw} h={rh} at={52}>
        <span style={{ ...big, fontSize: 110, ...gradText(f) }}>3 ways</span>
        <div style={{ display: "flex", gap: 10, marginTop: 22 }}>
          {["Disconnect", "Overlay", "DDC/CI"].map((m, i) => (
            <span
              key={m}
              style={{
                fontFamily: SANS,
                fontSize: 24,
                fontWeight: 600,
                color: C.text,
                padding: "8px 16px",
                borderRadius: 999,
                border: `1px solid ${C.line}`,
                background: "rgba(255,255,255,0.05)",
                opacity: tw(f - 70 - i * 6, [0, 10], [0, 1], Easing.linear),
              }}
            >
              {m}
            </span>
          ))}
        </div>
        <Caption>to turn off the other screens.</Caption>
      </Tile>
    </AbsoluteFill>
  );
};

const Automate: React.FC = () => {
  const f = useCurrentFrame();
  const cmd = "consolemode://start";
  const typed = Math.floor(interpolate(f, [20, 62], [0, cmd.length], clamp));
  const caret = Math.floor(f / 8) % 2 === 0 || (f > 20 && f < 62);
  const keys: { icon: IconName; label: string; at: number }[] = [
    { icon: "play", label: "Start", at: 105 },
    { icon: "menu", label: "Menu", at: 120 },
    { icon: "stop", label: "Stop", at: 135 },
  ];
  return (
    <AbsoluteFill>
      <Glow color={C.violet} y={760} opacity={0.14} />
      <Center top={110}>
        <Line words={["Automate", { t: "everything.", grad: true }]} at={2} size={112} stagger={6} />
      </Center>
      <div style={{ position: "absolute", top: 340, left: 0, right: 0, display: "flex", justifyContent: "center" }}>
        <div
          style={{
            minWidth: 900,
            padding: "30px 44px",
            borderRadius: 28,
            background: "linear-gradient(180deg,#141416,#0b0b0d)",
            border: `1px solid ${C.line}`,
            fontFamily: MONO,
            fontSize: 52,
            fontWeight: 500,
            color: C.text,
            opacity: tw(f, [8, 20], [0, 1], Easing.linear),
            display: "flex",
            alignItems: "center",
          }}
        >
          <span style={{ color: C.mint, marginRight: 24 }}>›</span>
          <span>{cmd.slice(0, typed)}</span>
          <span style={{ display: "inline-block", width: 26, height: 58, marginLeft: 4, background: C.mint, opacity: caret ? 1 : 0 }} />
        </div>
      </div>
      <div style={{ position: "absolute", top: 560, left: 0, right: 0, display: "flex", justifyContent: "center", gap: 40 }}>
        {keys.map((k, i) => {
          const enter = tw(f - 75 - i * 5, [0, 18], [0, 1]);
          const lit = interpolate(f, [k.at, k.at + 3, k.at + 14], [0, 1, 0.35], clamp);
          return (
            <div
              key={k.label}
              style={{
                width: 200,
                height: 200,
                borderRadius: 36,
                background: lit > 0.05 ? `linear-gradient(160deg, rgba(62,207,160,${lit}), rgba(56,198,255,${lit * 0.8}))` : "linear-gradient(180deg,#1a1a1d,#0e0e10)",
                border: `1.5px solid ${lit > 0.3 ? C.mint : "rgba(255,255,255,0.14)"}`,
                boxShadow: `0 ${24 - lit * 8}px 50px rgba(0,0,0,0.6), 0 0 ${60 * lit}px ${C.mint}88`,
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
                justifyContent: "center",
                gap: 14,
                opacity: enter,
                translate: `0 ${(1 - enter) * 80 + lit * 6}px`,
              }}
            >
              <Icon name={k.icon} size={64} color={lit > 0.5 ? "#03130d" : C.text} />
              <span style={{ fontFamily: SANS, fontSize: 30, fontWeight: 700, color: lit > 0.5 ? "#03130d" : C.text }}>{k.label}</span>
            </div>
          );
        })}
      </div>
      <Center top={860}>
        <Line words={["Links,", "command", "line", "and", "a", "local", "control", "API."]} at={92} size={40} weight={500} stagger={2} color={C.muted} />
      </Center>
    </AbsoluteFill>
  );
};

const Interfaces: React.FC = () => {
  const f = useCurrentFrame();
  const enterL = tw(f - 16, [0, 24], [0, 1]);
  const enterR = tw(f - 30, [0, 24], [0, 1]);
  const focus = 0.6 + 0.4 * Math.sin(f / 6);
  const W = 760;
  const H = 440;
  const label: React.CSSProperties = { fontFamily: SANS, fontSize: 40, fontWeight: 700, color: C.text, textAlign: "center", marginTop: 30, letterSpacing: "-0.02em" };
  return (
    <AbsoluteFill>
      <Glow color={C.mint} y={620} opacity={0.12} size={1700} />
      <Center top={100}>
        <Line words={["Mouse", "or", { t: "controller.", grad: true }]} at={2} size={104} stagger={5} />
      </Center>
      <div style={{ position: "absolute", top: 290, left: 0, right: 0, display: "flex", justifyContent: "center", gap: 80 }}>
        <div style={{ opacity: enterL, translate: `${(1 - enterL) * -80}px 0`, filter: `blur(${(1 - enterL) * 12}px)` }}>
          <div style={{ width: W, height: H, borderRadius: 18, background: "#1c1c1f", border: `1px solid ${C.line}`, overflow: "hidden", position: "relative" }}>
            <div style={{ height: 52, display: "flex", alignItems: "center", gap: 12, padding: "0 20px", borderBottom: `1px solid ${C.line}` }}>
              <Logo size={24} draw={1} />
              <span style={{ fontFamily: SANS, fontSize: 20, fontWeight: 600, color: C.text, flex: 1 }}>Console Mode</span>
              <span style={{ fontFamily: SANS, fontSize: 18, color: C.muted, letterSpacing: 18 }}>–□×</span>
            </div>
            <div style={{ padding: "26px 32px", display: "flex", flexDirection: "column", gap: 14 }}>
              {["Living room TV", "Monitor 1", "Monitor 2"].map((s, i) => (
                <div key={s} style={{ display: "flex", alignItems: "center", gap: 16, padding: "14px 18px", borderRadius: 12, background: i === 0 ? "rgba(62,207,160,0.12)" : "rgba(255,255,255,0.04)", border: `1px solid ${i === 0 ? C.mint + "88" : C.line}` }}>
                  <div style={{ width: 20, height: 20, borderRadius: 10, border: `2px solid ${i === 0 ? C.mint : C.muted}`, background: i === 0 ? `radial-gradient(${C.mint} 45%, transparent 50%)` : undefined }} />
                  <span style={{ fontFamily: SANS, fontSize: 24, fontWeight: 600, color: C.text, flex: 1 }}>{s}</span>
                  <span style={{ fontFamily: SANS, fontSize: 20, color: C.muted }}>{i === 0 ? "4K · 120 Hz" : "1440p"}</span>
                </div>
              ))}
            </div>
            <div style={{ position: "absolute", right: 32, bottom: 28, padding: "14px 36px", borderRadius: 999, background: C.mint, color: "#04110c", fontFamily: SANS, fontSize: 24, fontWeight: 700 }}>Play now</div>
          </div>
          <div style={label}>Desktop</div>
        </div>
        <div style={{ opacity: enterR, translate: `${(1 - enterR) * 80}px 0`, filter: `blur(${(1 - enterR) * 12}px)` }}>
          <div style={{ width: W, height: H, borderRadius: 18, background: "radial-gradient(120% 100% at 20% 0%, #1b2e2a, #050607)", border: `1px solid ${C.line}`, overflow: "hidden", position: "relative", padding: 40, boxSizing: "border-box" }}>
            <div style={{ fontFamily: SANS, fontSize: 40, fontWeight: 800, color: C.text, letterSpacing: "-0.03em" }}>Console Mode</div>
            <div style={{ display: "flex", gap: 22, marginTop: 36 }}>
              {(["play", "screen", "menu"] as IconName[]).map((ic, i) => (
                <div
                  key={ic}
                  style={{
                    width: 206,
                    height: 190,
                    borderRadius: 22,
                    background: i === 0 ? "linear-gradient(160deg,#3ecfa0,#1f9a76)" : "rgba(255,255,255,0.06)",
                    border: i === 0 ? `3px solid rgba(255,255,255,${focus})` : `1px solid ${C.line}`,
                    boxShadow: i === 0 ? `0 0 ${40 * focus}px ${C.mint}88` : undefined,
                    display: "flex",
                    flexDirection: "column",
                    justifyContent: "space-between",
                    padding: 22,
                    boxSizing: "border-box",
                  }}
                >
                  <Icon name={ic} size={48} color={i === 0 ? "#03130d" : C.text} />
                  <span style={{ fontFamily: SANS, fontSize: 28, fontWeight: 700, color: i === 0 ? "#03130d" : C.text }}>{["Play", "Screens", "Settings"][i]}</span>
                </div>
              ))}
            </div>
            <div style={{ position: "absolute", left: 40, bottom: 30, display: "flex", gap: 30, fontFamily: SANS, fontSize: 22, color: C.muted, alignItems: "center" }}>
              {[
                ["A", "#5fd36f", "Select"],
                ["B", "#ff6b6b", "Back"],
              ].map(([b, col, t]) => (
                <span key={b} style={{ display: "flex", alignItems: "center", gap: 10 }}>
                  <span style={{ width: 34, height: 34, borderRadius: 17, border: `2px solid ${col}`, color: col, fontWeight: 800, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 18 }}>{b}</span>
                  {t}
                </span>
              ))}
            </div>
          </div>
          <div style={label}>Console</div>
        </div>
      </div>
      <Center top={900}>
        <Line words={["In", "English,", "Português", "and", "Español."]} at={96} size={40} weight={500} stagger={3} color={C.muted} />
      </Center>
    </AbsoluteFill>
  );
};

const Trust: React.FC = () => (
  <AbsoluteFill>
    <Glow color={C.violet} y={540} x={1200} opacity={0.12} />
    <Center>
      <div style={{ width: 1400, margin: "0 auto" }}>
        <Line words={["No", "admin."]} at={0} size={132} stagger={4} align="flex-start" />
        <div style={{ height: 14 }} />
        <Line words={["Updates", "itself."]} at={15} size={132} stagger={4} align="flex-start" color={C.muted} />
        <div style={{ height: 14 }} />
        <Line words={[{ t: "Free", grad: true }, { t: "and", grad: true }, { t: "open", grad: true }, { t: "source.", grad: true }]} at={30} size={132} stagger={4} align="flex-start" />
      </div>
    </Center>
  </AbsoluteFill>
);

const Finale: React.FC = () => {
  const f = useCurrentFrame();
  const { fps } = useVideoConfig();
  const pop = spring({ frame: f, fps, config: { damping: 14, stiffness: 110 } });
  const ring = tw(f, [0, 50], [0, 1]);
  const end = tw(f, [205, 240], [0, 1], Easing.inOut(Easing.cubic));
  const btn = spring({ frame: f - 95, fps, config: { damping: 16, stiffness: 120 } });
  return (
    <AbsoluteFill style={{ opacity: 1 - end }}>
      <Glow color={C.mint} y={470} opacity={0.2 + pop * 0.08} size={1600} />
      <div
        style={{
          position: "absolute",
          left: 960 - 400 * ring,
          top: 330 - 400 * ring,
          width: 800 * ring,
          height: 800 * ring,
          borderRadius: "50%",
          border: `3px solid ${C.mint}`,
          opacity: (1 - ring) * 0.8,
        }}
      />
      <Center top={200}>
        <div style={{ display: "flex", justifyContent: "center", scale: String(0.6 + pop * 0.4) }}>
          <Logo size={200} draw={1} glow={pop} />
        </div>
        <div style={{ height: 40 }} />
        <Line words={["Console", "Mode"]} at={6} size={170} weight={800} stagger={5} />
        <div style={{ height: 22 }} />
        <Line words={["Your", "PC.", { t: "Now", grad: true }, { t: "a", grad: true }, { t: "console.", grad: true }]} at={40} size={62} weight={600} stagger={4} color={C.muted} />
      </Center>
      <div style={{ position: "absolute", top: 830, left: 0, right: 0, display: "flex", flexDirection: "column", alignItems: "center", gap: 26 }}>
        <div
          style={{
            padding: "20px 50px",
            borderRadius: 999,
            background: C.text,
            color: "#000",
            fontFamily: SANS,
            fontSize: 34,
            fontWeight: 700,
            letterSpacing: "-0.01em",
            opacity: btn,
            scale: String(0.85 + btn * 0.15),
          }}
        >
          Download for Windows
        </div>
        <div style={{ fontFamily: SANS, fontSize: 30, fontWeight: 500, color: C.muted, opacity: tw(f, [110, 125], [0, 1], Easing.linear) }}>github.com/lippdev/consolemode</div>
      </div>
    </AbsoluteFill>
  );
};

// ───────────────────────── film ─────────────────────────

export const Keynote: React.FC = () => {
  const [handle] = useState(() => delayRender("Loading fonts"));
  useEffect(() => {
    Promise.all([
      document.fonts.load(`800 100px 'Inter Variable'`),
      document.fonts.load(`500 40px 'JetBrains Mono Variable'`),
    ]).then(
      () => continueRender(handle),
      () => continueRender(handle),
    );
  }, [handle]);

  return (
    <AbsoluteFill style={{ background: C.bg, overflow: "hidden" }}>
      <Audio src={staticFile("keynote/soundtrack.mp3")} />
      <Scene {...S.open}>
        <ColdOpen />
      </Scene>
      <Scene {...S.title}>
        <Title />
      </Scene>
      <Scene {...S.click}>
        <OneClick />
      </Scene>
      <Scene {...S.restore}>
        <Restore />
      </Scene>
      <Scene {...S.launchers}>
        <Launchers />
      </Scene>
      <Scene {...S.home}>
        <HoldHome />
      </Scene>
      <Scene {...S.menu}>
        <SessionMenu />
      </Scene>
      <Scene {...S.bento}>
        <Bento />
      </Scene>
      <Scene {...S.automate}>
        <Automate />
      </Scene>
      <Scene {...S.interfaces}>
        <Interfaces />
      </Scene>
      <Scene {...S.trust}>
        <Trust />
      </Scene>
      <Sequence from={S.finale.from} durationInFrames={S.finale.dur}>
        <Finale />
      </Sequence>
    </AbsoluteFill>
  );
};
